// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaAPI.Data;

#nullable disable

namespace TiendaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TiendaAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Hogar"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Deportes"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Accesorios"
                        });
                });

            modelBuilder.Entity("TiendaAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Laptop ligera con procesador de alto rendimiento para trabajo y estudio.",
                            Imagen = "https://placehold.co/600x400/png?text=Laptop+Pro+14",
                            Nombre = "Laptop Pro 14",
                            Precio = 18999.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descripcion = "Teléfono con cámara avanzada, gran pantalla y batería de larga duración.",
                            Imagen = "https://placehold.co/600x400/png?text=Smartphone+X",
                            Nombre = "Smartphone X",
                            Precio = 14999.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 4,
                            Descripcion = "Sonido envolvente, cancelación de ruido y estuche de carga compacta.",
                            Imagen = "https://placehold.co/600x400/png?text=Audifonos",
                            Nombre = "Audífonos inalámbricos",
                            Precio = 1999.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            Descripcion = "Pantalla 4K con sistema inteligente y conexión para streaming.",
                            Imagen = "https://placehold.co/600x400/png?text=Smart+TV",
                            Nombre = "Smart TV 55 pulgadas",
                            Precio = 12999.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            Descripcion = "Prepara café en pocos minutos con control de intensidad y temporizador.",
                            Imagen = "https://placehold.co/600x400/png?text=Cafetera",
                            Nombre = "Cafetera automática",
                            Precio = 3299.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            Descripcion = "Calzado deportivo cómodo y resistente para entrenamiento diario.",
                            Imagen = "https://placehold.co/600x400/png?text=Tenis+Running",
                            Nombre = "Tenis Running",
                            Precio = 2499.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 4,
                            Descripcion = "Mochila resistente con compartimento acolchado para laptop.",
                            Imagen = "https://placehold.co/600x400/png?text=Mochila",
                            Nombre = "Mochila urbana",
                            Precio = 1199.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 3,
                            Descripcion = "Bicicleta lista para rutas urbanas y senderos ligeros.",
                            Imagen = "https://placehold.co/600x400/png?text=Bicicleta",
                            Nombre = "Bicicleta de montaña",
                            Precio = 8999.00m
                        });
                });

            modelBuilder.Entity("TiendaAPI.Models.Product", b =>
                {
                    b.HasOne("TiendaAPI.Models.Category", "Categoria")
                        .WithMany("Products")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TiendaAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
